
[profile.default]
src = "src"
out = "out"
libs = ["lib"]

script = 'script'
optimizer = true
optimizer_runs = 999999


[fmt]
line_length=120
multiline_func_header='all'
bracket_spacing=true
wrap_comments=true
